
web:
  build: .
  ports:
   - 80:80
  volumes:
   - <--absolute-path-to-the-directory-->/django-uwsgi-nginx/code:/home/code
  links:
   - database:postgres
database:
  image: postgres
  volumes:
   - postgres-data:/var/lib/postgresql/data